version: '2'

services:
  web:
    build:
      context: ./
      dockerfile: web.docker
    networks:
      - book
    volumes:
      - ./:/var/www
    ports:
      - "8888:80"
    links:
      - app
  app:
    build:
      context: ./
      dockerfile: app.docker
    networks:
      - book
    volumes:
      - ./:/var/www
    links:
      - db
    environment:
      - DB_PORT=3306
      - DB_HOST=db
  db:
    image: mysql:5.7
    container_name: mysql_db
    networks:
      - book
    environment:
      - "MYSQL_USER=${DB_DATABASE}"
      - "MYSQL_PASSWORD=${DB_PASSWORD}"
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - "33061:3306"
    
  pma:
    container_name: pma
    image: phpmyadmin/phpmyadmin
    ports:
      - "9999:80"
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    networks:
      - book

networks:
  book:
    driver: bridge